#%RAML 1.0 NamedExample
-
  reportTimestamp: "2021-10-19T03:00:11.113Z"
  summary:
    production:
      totalVCores: 4
      allocatedVcores: 0.2
      avgCPUusage: 2.228793796267745
    sandbox:
      totalVCores: 8
      allocatedVcores: 2.5
      avgCPUusage: 3.8210614917100344

    design:
      totalVCores: 8
      allocatedVcores: 0 
      avgCPUusage: 0

    startDatetime: "2021-10-20T10:59:20.924Z"
    endDatetime: "2021-10-20T11:59:20.923Z"
  businessGroupLevelDetails:
    -
      businessGroupName: "MuleSoft"
      businessGroupId: "aaaabbbb-1111-2222-cccc-3333dddd4444"
      production:
        applications:
          -      
            application: "customer-exp-api"
            environment: "Production"
            environmentType: "Production"
            businessGroup: "aaaabbbb-1111-2222-cccc-3333dddd4444"
            workerType: 0.1
            workerAmount: 2
            status: STARTED"
            averageCPUUtilisation: 1.5252919751183
            endDate: "2021-10-20T11:59:20.923Z"
            startDate: "2021-10-20T10:59:20.924Z"
        totalVCores: 4
        allocatedVcores: 0.2
        avgWeightedCpu: 2.228793796267745

      sandbox:
        applications:
          -       
            application: "customer-exp-api"
            environment: "Development"
            environmentType: "Sandbox"
            businessGroup: "aaaabbbb-1111-2222-cccc-3333dddd4444"
            workerType: 0.2
            workerAmount: 1
            status: "STARTED"
            averageCPUUtilisation: 0.2909737458037545
            endDate: "2021-10-20T11:59:20.923Z"
            startDate: "2021-10-20T10:59:20.924Z"
          -
            application: "acccounts-exp-api"
            environment: "Development"
            environmentType: "Sandbox"
            businessGroup: "aaaabbbb-1111-2222-cccc-3333dddd4444"
            workerType: 0.2
            workerAmount: 1
            status: "STARTED"
            averageCPUUtilisation: 0.2909737458037545
            endDate: "2021-10-20T11:59:20.923Z"
            startDate: "2021-10-20T10:59:20.924Z"
        totalVCores: 1.5
        allocatedVcores: 0.3
        avgWeightedCpu: 0.1306756655613963

      design:
        applications: []
        totalVCores: 2
        allocatedVcores: 0
        avgWeightedCpu: 0
-
  reportTimestamp: "2021-10-18T03:00:11.113Z"
  summary:
    production:
      totalVCores: 4
      allocatedVcores: 0.1
      avgCPUusage: 2.228793796267745
    sandbox:
      totalVCores: 8
      allocatedVcores: 2.5
      avgCPUusage: 3.8210614917100344

    design:
      totalVCores: 8
      allocatedVcores: 0 
      avgCPUusage: 0

    startDatetime: "2021-10-20T10:59:20.924Z"
    endDatetime: "2021-10-20T11:59:20.923Z"
  businessGroupLevelDetails:
    -
      businessGroupName: "MuleSoft"
      businessGroupId: "aaaabbbb-1111-2222-cccc-3333dddd4444"
      production:
        applications:
          -      
            application: "customer-exp-api"
            environment: "Production"
            environmentType: "Production"
            businessGroup: "aaaabbbb-1111-2222-cccc-3333dddd4444"
            workerType: 0.1
            workerAmount: 1
            status: STARTED"
            averageCPUUtilisation: 1.5252919751183
            endDate: "2021-10-20T11:59:20.923Z"
            startDate: "2021-10-20T10:59:20.924Z"
        totalVCores: 4
        allocatedVcores: 0.2
        avgWeightedCpu: 2.228793796267745

      sandbox:
        applications:
          -       
            application: "customer-exp-api"
            environment: "Development"
            environmentType: "Sandbox"
            businessGroup: "aaaabbbb-1111-2222-cccc-3333dddd4444"
            workerType: 0.2
            workerAmount: 1
            status: "STARTED"
            averageCPUUtilisation: 0.2909737458037545
            endDate: "2021-10-20T11:59:20.923Z"
            startDate: "2021-10-20T10:59:20.924Z"
          -
            application: "acccounts-exp-api"
            environment: "Development"
            environmentType: "Sandbox"
            businessGroup: "aaaabbbb-1111-2222-cccc-3333dddd4444"
            workerType: 0.2
            workerAmount: 1
            status: "STARTED"
            averageCPUUtilisation: 0.2909737458037545
            endDate: "2021-10-20T11:59:20.923Z"
            startDate: "2021-10-20T10:59:20.924Z"
        totalVCores: 1.5
        allocatedVcores: 0.3
        avgWeightedCpu: 0.1306756655613963

      design:
        applications: []
        totalVCores: 2
        allocatedVcores: 0
        avgWeightedCpu: 0