#%RAML 1.0
title: CPU Utilisation Toolkit API
description: | 
  The CPU Utilisation Toolkit is an extensible Mule application intended to collect and aggregate metrics related to CPU usage of applications deployed on CloudHub, and to generate and publish reports of these metrics to various systems. This is the API descriptor for said application. 

version: v1
protocols: 
  - HTTPS
  - HTTP

securitySchemes:
  clientId: !include securitySchemes/clientId.raml

traits:
  receiveAnypointOrgId: !include traits/receiveAnypointOrgId.raml
  receiveConnectedApp: !include traits/receiveConnectedApp.raml
  receivePlatformUser: !include traits/receivePlatformUser.raml
  receiveExcludeLists: !include traits/receiveExcludeLists.raml

uses:
  dataTypesLibrary: libraries/dataTypes.raml

/cpu-metrics:
  is:
    - receiveAnypointOrgId
    - receiveConnectedApp
    - receivePlatformUser
    - receiveExcludeLists
  get:
    description: Retrieves a snapshot of the current CPU usage metrics. Currently applications deployed to CloudHub are considered. 
    responses:
      200:
        body:
          application/json:
            type: dataTypesLibrary.metrics
            example: !include examples/cpuUtilisationMetrics.raml
  
  post:
    body:
      application/json:
        type: dataTypesLibrary.loaders
        example: !include examples/strategies.raml
    responses:
      201:    

/reports:
  securedBy:
    - clientId
  get:
    description: Gets all of the currently held vCore usage metric reports
    responses:
      200:
        body:
          application/json:
            type: dataTypesLibrary.reports[]
            example: !include examples/reportList.raml
  post:
    description: Creates a report of the historic metrics and pushes to the determined location e.g. an email attachment 
    body:
      application/json:
        properties:
          reports:
            properties:
              email?: dataTypesLibrary.emailReport
    responses:
      201:
  delete:
    description: Deletes all currently held metrics reports 
    responses:
      200: